import { useState } from 'react'
import { Modal, Upload, Button, Alert, Typography, Space, message } from 'antd'
import { InboxOutlined } from '@ant-design/icons'
import type { UploadProps } from 'antd'
import { useRadarStore } from '@/stores/radarStore'
import { useI18n } from '@/locales'
import type { VersionTimeline, VersionEvent, TimelineInfo } from '@/types/versionTimeline'
import styles from './TimelineImportModal.module.css'

const { Dragger } = Upload
const { Text, Title } = Typography

interface TimelineImportModalProps {
  open: boolean
  onClose: () => void
}

interface ParsedTimeline {
  name?: string
  info: TimelineInfo
  events: VersionEvent[]
}

interface ParseResult {
  isValid: boolean
  data: ParsedTimeline | null
  errors: string[]
  warnings: string[]
}

function validateTimelineData(data: unknown): ParseResult {
  const errors: string[] = []
  const warnings: string[] = []

  if (!data || typeof data !== 'object') {
    return { isValid: false, data: null, errors: ['无效的 JSON 数据'], warnings: [] }
  }

  const obj = data as Record<string, unknown>

  // Validate info
  if (!obj.info || typeof obj.info !== 'object') {
    errors.push('缺少 info 字段')
  } else {
    const info = obj.info as Record<string, unknown>
    if (!info.title || typeof info.title !== 'string') {
      errors.push('info.title 是必需的字符串字段')
    }
  }

  // Validate events
  if (!Array.isArray(obj.events)) {
    errors.push('events 必须是数组')
  } else {
    obj.events.forEach((event, index) => {
      if (!event || typeof event !== 'object') {
        errors.push(`events[${index}] 必须是对象`)
        return
      }
      const e = event as Record<string, unknown>
      if (typeof e.year !== 'number') {
        errors.push(`events[${index}].year 必须是数字`)
      }
      if (!e.title || typeof e.title !== 'string') {
        errors.push(`events[${index}].title 是必需的字符串字段`)
      }
      if (e.type && !['major', 'minor', 'patch', 'milestone'].includes(e.type as string)) {
        warnings.push(`events[${index}].type "${e.type}" 不是有效类型，将使用默认值 "minor"`)
      }
    })
  }

  if (errors.length > 0) {
    return { isValid: false, data: null, errors, warnings }
  }

  // Normalize data
  const info = obj.info as TimelineInfo
  const events = (obj.events as Array<Record<string, unknown>>).map((e, i) => ({
    id: (e.id as string) || `imported-${i}`,
    year: e.year as number,
    title: e.title as string,
    description: e.description as string | undefined,
    type: (['major', 'minor', 'patch', 'milestone'].includes(e.type as string)
      ? e.type
      : 'minor') as VersionEvent['type'],
    position: 'top' as const,
    highlight: Array.isArray(e.highlight) ? e.highlight as string[] : undefined,
    icon: e.icon as string | undefined,
  }))

  return {
    isValid: true,
    data: {
      name: obj.name as string | undefined,
      info,
      events,
    },
    errors: [],
    warnings,
  }
}

export function TimelineImportModal({ open, onClose }: TimelineImportModalProps) {
  const { t } = useI18n()
  const { importVersionTimeline } = useRadarStore()
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<ParseResult | null>(null)

  const handleClose = () => {
    setResult(null)
    onClose()
  }

  const handleFileRead = async (file: File) => {
    setLoading(true)
    try {
      const text = await file.text()
      const json = JSON.parse(text)
      const parseResult = validateTimelineData(json)
      setResult(parseResult)
    } catch (error) {
      setResult({
        isValid: false,
        data: null,
        errors: ['JSON 解析失败，请检查文件格式'],
        warnings: [],
      })
    } finally {
      setLoading(false)
    }
    return false
  }

  const handleConfirm = () => {
    if (!result?.isValid || !result.data) return

    const timeline: VersionTimeline = {
      id: '', // Will be generated by store
      name: result.data.name || result.data.info.title || '导入的时间轴',
      order: 0, // Will be set by store
      isVersionTimeline: true,
      info: result.data.info,
      events: result.data.events,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }

    importVersionTimeline(timeline)
    message.success(t.toolbar.importSuccess || '导入成功')
    handleClose()
  }

  const uploadProps: UploadProps = {
    accept: '.json',
    beforeUpload: handleFileRead,
    showUploadList: false,
    maxCount: 1,
  }

  const renderPreview = () => {
    if (!result?.data) return null

    const { data } = result
    const eventsByType = {
      major: data.events.filter(e => e.type === 'major').length,
      minor: data.events.filter(e => e.type === 'minor').length,
      milestone: data.events.filter(e => e.type === 'milestone').length,
      patch: data.events.filter(e => e.type === 'patch').length,
    }

    const years = data.events.map(e => e.year)
    const minYear = Math.min(...years)
    const maxYear = Math.max(...years)

    return (
      <div className={styles.preview}>
        <Title level={5}>{t.toolbar.dataPreview || '数据预览'}</Title>
        <Space direction="vertical" style={{ width: '100%' }} size="small">
          <Text><strong>{t.versionTimeline.title || '时间轴'}:</strong> {data.info.title}</Text>
          {data.info.company && (
            <Text><strong>{t.versionTimeline.company || '公司'}:</strong> {data.info.company}</Text>
          )}
          <Text><strong>{t.versionTimeline.eventCount || '事件数量'}:</strong> {data.events.length}</Text>
          <Text><strong>{t.versionTimeline.timeRange || '时间范围'}:</strong> {minYear} - {maxYear}</Text>
          <div className={styles.eventTypes}>
            {eventsByType.milestone > 0 && (
              <span className={styles.badge}>{t.versionTimeline.milestone || '里程碑'}: {eventsByType.milestone}</span>
            )}
            {eventsByType.major > 0 && (
              <span className={styles.badge}>{t.versionTimeline.major || '重大'}: {eventsByType.major}</span>
            )}
            {eventsByType.minor > 0 && (
              <span className={styles.badge}>{t.versionTimeline.minor || '次要'}: {eventsByType.minor}</span>
            )}
          </div>
        </Space>
      </div>
    )
  }

  return (
    <Modal
      title={t.versionTimeline.importTimeline || '导入时间轴'}
      open={open}
      onCancel={handleClose}
      confirmLoading={loading}
      footer={
        result?.isValid
          ? [
              <Button key="cancel" onClick={handleClose}>
                {t.common.cancel || '取消'}
              </Button>,
              <Button key="confirm" type="primary" onClick={handleConfirm}>
                {t.toolbar.confirmImport || '确认导入'}
              </Button>,
            ]
          : [
              <Button key="cancel" onClick={handleClose}>
                {t.common.cancel || '关闭'}
              </Button>,
            ]
      }
      width={520}
    >
      {!result ? (
        <Dragger {...uploadProps} className={styles.dragger}>
          <p className="ant-upload-drag-icon">
            <InboxOutlined />
          </p>
          <p className="ant-upload-text">{t.versionTimeline.dragJson || '点击或拖拽 JSON 文件到此处'}</p>
          <p className="ant-upload-hint">{t.versionTimeline.jsonHint || '支持导出的时间轴 JSON 格式'}</p>
        </Dragger>
      ) : (
        <div className={styles.result}>
          {result.errors.length > 0 && (
            <Alert
              type="error"
              message={t.toolbar.importFailed || '导入失败'}
              description={
                <ul className={styles.errorList}>
                  {result.errors.map((e, i) => (
                    <li key={i}>{e}</li>
                  ))}
                </ul>
              }
              showIcon
            />
          )}
          {result.warnings.length > 0 && (
            <Alert
              type="warning"
              message={t.toolbar.warning || '警告'}
              description={
                <ul className={styles.errorList}>
                  {result.warnings.map((w, i) => (
                    <li key={i}>{w}</li>
                  ))}
                </ul>
              }
              showIcon
              style={{ marginTop: 16 }}
            />
          )}
          {result.isValid && (
            <Alert
              type="success"
              message={t.toolbar.parseSuccess || '解析成功'}
              description={t.toolbar.confirmToImport || '数据格式正确，请确认后导入'}
              showIcon
            />
          )}
          {renderPreview()}
          <Button
            type="link"
            onClick={() => setResult(null)}
            style={{ marginTop: 16, padding: 0 }}
          >
            {t.toolbar.reselect || '重新选择文件'}
          </Button>
        </div>
      )}
    </Modal>
  )
}

export default TimelineImportModal
